/**
 * Soalan Kuiz Jikey — dari dokumen rasmi
 * 5 Bahagian (Topik) × 15 soalan = 75 soalan
 */

const QUIZ_TOPICS = [
  {
    id: "bahagian-a",
    name: "Bahagian A: Pengenalan & Sejarah Jikey",
    icon: "📜",
    color: "#7B1E3A",
    description: "Asal-usul, sejarah & latar belakang kesenian Jikey di Malaysia.",
    passThreshold: 70,
    maxPoints: 100,
    questions: [
      { question: "Jikey ialah sejenis seni apa dalam masyarakat Melayu?", options: ["Silat tempur", "Wayang kulit", "Teater tradisional rakyat", "Lagu rakyat solo"], correct: 2 },
      { question: "Jikey paling sinonim dengan negeri-negeri mana di Malaysia pada era 1960–1970-an?", options: ["Kelantan dan Terengganu", "Kedah dan Perlis", "Melaka dan Johor", "Sabah dan Sarawak"], correct: 1 },
      { question: "Jikey digolongkan dalam kategori apa dalam pangkalan data Pemetaan Budaya JKKN?", options: ["Makanan tradisional", "Busana tradisional", "Seni persembahan tradisional", "Permainan kanak-kanak"], correct: 2 },
      { question: "Dari sudut bentuk persembahan, Jikey sering dirujuk sebagai:", options: ["Tarian istana eksklusif", "Teater muzikal rakyat berunsur komedi", "Pertandingan nyanyian solo", "Ritual keagamaan"], correct: 1 },
      { question: "Pada abad ke-20, Jikey berfungsi terutama sebagai hiburan untuk:", options: ["Golongan istana sahaja", "Pekerja lombong", "Masyarakat kampung dan komuniti setempat", "Pelajar sekolah berasrama"], correct: 2 },
      { question: "Dalam konteks utara Semenanjung, Jikey terkenal sebagai teater rakyat untuk:", options: ["Menceritakan sejarah kolonial rasmi", "Menghibur dan menyampaikan pesan sosial", "Upacara keagamaan wajib", "Latihan ketenteraan"], correct: 1 },
      { question: "Agensi kerajaan yang diiktiraf sebagai rujukan utama maklumat rasmi tentang Jikey ialah:", options: ["Arkib Negara Malaysia", "Istana Negara", "Jabatan Kebudayaan dan Kesenian Negara (JKKN)", "Perpustakaan Negara Malaysia"], correct: 2 },
      { question: "Menurut JKKN, Jikey kini dikategorikan sebagai seni tradisi yang:", options: ["Masih sangat meluas dan dominan", "Semakin malap dan memerlukan pemuliharaan", "Baru diperkenalkan selepas 2000", "Hanya diamalkan di luar negara"], correct: 1 },
      { question: "Sumber rasmi menyatakan Jikey sangat sinonim dengan masyarakat Melayu di:", options: ["Pantai Timur", "Seluruh Nusantara secara sama rata", "Utara Semenanjung Malaysia", "Borneo"], correct: 2 },
      { question: "Dalam laporan Bernama, Jikey disebut sebagai lambang apa?", options: ["Kemajuan teknologi", "Perpaduan kaum", "Kuasa politik tempatan", "Pendidikan tinggi"], correct: 1 },
      { question: "Jikey dikaitkan dengan watak pelbagai bangsa kerana:", options: ["Peraturan undang-undang", "Tradisi pementasan yang menampilkan Cina dan India", "Ia program sekolah sahaja", "Arahan persekutuan khas"], correct: 1 },
      { question: "Tempat yang disebut masih mempunyai kumpulan Jikey aktif ialah:", options: ["Bandaraya Alor Setar sahaja", "Kangar sahaja", "Langkawi", "Kuala Lumpur"], correct: 2 },
      { question: "Dalam keratan Bernama, berapa banyak kumpulan Jikey disebut masih aktif di Kedah ketika laporan itu?", options: ["Satu kumpulan", "Dua kumpulan", "Tiga kumpulan", "Lebih sepuluh kumpulan"], correct: 1 },
      { question: "Pemetaan Budaya JKKN berperanan sebagai apa bagi maklumat Jikey?", options: ["Arkib video tertutup", "Gerbang maklumat/direktori seni budaya", "Sekolah latihan wajib", "Pusat tiket persembahan"], correct: 1 },
      { question: "Secara umum, Jikey boleh diringkaskan sebagai:", options: ["Nyanyian solo tanpa muzik", "Pertandingan tulisan jawi", "Teater rakyat hiburan yang menggabungkan lakonan, muzik dan tarian", "Upacara perkahwinan khusus"], correct: 2 }
    ]  },
  {
    id: "bahagian-b",
    name: "Bahagian B: Bentuk & Struktur Persembahan Jikey",
    icon: "🎭",
    color: "#1A5C4B",
    description: "Bentuk persembahan, struktur teater & elemen pementasan Jikey.",
    passThreshold: 70,
    maxPoints: 100,
    questions: [
      { question: "Menurut JKKN dan Bernama, Jikey biasanya dipersembahkan dalam bentuk:", options: ["Bacaan puisi senyap", "Teater muzikal berkonsep usik-mengusik (komedi)", "Debat formal", "Ceramah ilmiah"], correct: 1 },
      { question: "Jikey menampilkan gabungan utama elemen berikut:", options: ["Sukan, silat, memanah", "Muzik, nyanyian, tarian dan lakonan", "Lukisan dan ukiran kayu", "Persembahan boneka tangan"], correct: 1 },
      { question: "Dialog dalam Jikey lazimnya bercirikan:", options: ["Bahasa baku formal sahaja", "Bahasa asing tanpa terjemahan", "Dialog kelakar dan lucu", "Bacaan teks undang-undang"], correct: 2 },
      { question: "Suasana persembahan Jikey biasanya:", options: ["Sangat formal dan kaku", "Senyap tanpa penonton bersuara", "Santai dengan interaksi dan gelak tawa penonton", "Hanya dalam dewan rasmi kerajaan"], correct: 2 },
      { question: "Pementasan Jikey boleh diadakan di:", options: ["Gelanggang terbuka atau pentas sementara", "Makmal sains sahaja", "Lapangan terbang", "Bilik darjah sahaja"], correct: 0 },
      { question: "Dalam struktur persembahan, watak pelawak dalam Jikey berfungsi untuk:", options: ["Menyampaikan khutbah agama", "Menghidupkan unsur komedi dan usik-mengusik", "Mengurus kewangan kumpulan", "Menjaga kostum"], correct: 1 },
      { question: "Kebiasaannya Jikey melibatkan:", options: ["Seorang pelakon tunggal", "Sekumpulan pelakon dengan pelbagai watak", "Hanya pemuzik tanpa pelakon", "Hanya penceramah"], correct: 1 },
      { question: "Susun atur asas persembahan Jikey biasanya bermula dengan:", options: ["Pertarungan fizikal", "Pengenalan watak dan suasana secara berperingkat", "Pengundian penonton", "Tayangan filem"], correct: 1 },
      { question: "Interaksi antara pelakon Jikey lazimnya berupa:", options: ["Dialog serius dan tegang sepenuhnya", "Usik-mengusik, sindiran dan humor", "Diam tanpa suara", "Bacaan skrip rasmi kerajaan"], correct: 1 },
      { question: "Jikey dikatakan sebagai teater komunal kerana:", options: ["Hanya untuk komuniti seni elit", "Melibatkan komuniti setempat sebagai penonton dan penyokong", "Ia disiar hanya di televisyen", "Tiada siapa yang boleh hadir menonton"], correct: 1 },
      { question: "Dalam persembahan di program JKKN seperti temasya dan festival, Jikey biasanya dijadualkan:", options: ["Waktu pagi sahaja", "Pada malam hari sebagai hiburan utama", "Waktu pejabat sahaja", "Ketika rehat tengah hari"], correct: 1 },
      { question: "Dari sudut durasi, persembahan Jikey di program kebudayaan cenderung:", options: ["Beberapa minit sahaja", "Lebih panjang daripada sekadar sketsa ringkas", "30 saat", "1 minit"], correct: 1 },
      { question: "Struktur persembahan yang menampilkan pelbagai bangsa dalam Jikey bertujuan:", options: ["Mengelirukan penonton", "Menonjolkan kepelbagaian dan perpaduan", "Menyekat interaksi", "Menjadi ritual tertutup"], correct: 1 },
      { question: "Dari perspektif pementasan, kostum dan topeng lucu dalam Jikey berperanan untuk:", options: ["Menyembunyikan identiti kumpulan", "Menguatkan elemen komedi dan watak", "Mengurangkan minat penonton", "Memenuhi syarat undang-undang"], correct: 1 },
      { question: "Jikey dikira unik kerana:", options: ["Tiada muzik langsung", "Menggabungkan hiburan rakyat dengan mesej sosial dalam satu bentuk teater", "Hanya dibaca dari buku", "Tidak melibatkan penonton"], correct: 1 }
    ]  },
  {
    id: "bahagian-c",
    name: "Bahagian C: Watak, Kostum & Muzik Jikey",
    icon: "🥁",
    color: "#C5A028",
    description: "Watak, kostum, muzik tradisi & instrumen dalam Jikey.",
    passThreshold: 70,
    maxPoints: 100,
    questions: [
      { question: "Antara watak utama yang disebut dalam laporan Bernama tentang Jikey ialah:", options: ["Doktor dan jururawat", "Lelaki Benggali, pelawak, raja dan wira", "Guru dan murid", "Pemandu teksi"], correct: 1 },
      { question: "Jikey menampilkan watak pelbagai bangsa seperti:", options: ["Hanya Melayu", "Hanya Arab", "Cina dan India", "Hanya Eropah"], correct: 2 },
      { question: "Fungsi watak raja dalam Jikey lazimnya:", options: ["Menjadi pemuzik utama", "Melambangkan kuasa dan struktur sosial", "Mengurus logistik", "Menjual tiket"], correct: 1 },
      { question: "Watak wira dalam Jikey sering digambarkan sebagai:", options: ["Penakut", "Berani dan mengatasi cabaran", "Pendiam sepenuhnya", "Penonton biasa"], correct: 1 },
      { question: "Dalam persembahan JKKN, pelakon Jikey biasanya memakai:", options: ["Pakaian rasmi pejabat", "Topeng atau kostum yang melucukan", "Pakaian seragam tentera", "Jubah graduasi"], correct: 1 },
      { question: "Fungsi utama kostum lucu dalam Jikey ialah untuk:", options: ["Menyembunyikan seni tersebut", "Meningkatkan unsur komedi dan identiti watak", "Mematuhi kod sekolah", "Mengurangkan tumpuan penonton"], correct: 1 },
      { question: "Dari sudut muzik, Jikey diklasifikasikan sebagai:", options: ["Pertandingan koir", "Nyanyian solo sahaja", "Persembahan dengan muzik iringan", "Tutur kata tanpa bunyi"], correct: 2 },
      { question: "Instrumen muzik tradisional yang lazim digunakan dalam teater rakyat utara seperti Jikey termasuk kumpulan:", options: ["Piano dan biola klasik Barat sahaja", "Gitar elektrik dan drum moden", "Alat pukul dan ritma tradisi (gendang/rebana, dll.)", "Hanya rekoder"], correct: 2 },
      { question: "Iringan muzik dalam Jikey berfungsi untuk:", options: ["Mengganggu dialog", "Mengiringi nyanyian, tarian dan pergerakan watak", "Menggantikan pelakon", "Mengisi masa rehat"], correct: 1 },
      { question: "Nyanyian dalam Jikey boleh memuatkan:", options: ["Hanya zikir", "Lirik yang berkait dengan jalan cerita dan suasana", "Iklan komersial sahaja", "Hanya abjad"], correct: 1 },
      { question: "Hubungan antara pelawak dan muzik dalam Jikey selalunya:", options: ["Tiada kaitan", "Muzik menekankan punchline dan gerak lucu", "Muzik berhenti bila pelawak muncul", "Pelawak tidak dibenarkan bercakap"], correct: 1 },
      { question: "Watak pelbagai bangsa dalam Jikey menyumbang kepada:", options: ["Ketegangan kaum", "Gambaran harmoni dan interaksi antara etnik", "Pengasingan sosial", "Pengurangan penonton"], correct: 1 },
      { question: "Kostum khas bagi watak Benggali atau India dalam Jikey berupaya:", options: ["Menyembunyikan watak itu sepenuhnya", "Membezakan identiti dan latar belakang watak", "Menyamakan semua watak", "Menghilangkan elemen cerita"], correct: 1 },
      { question: "Dari sudut penghayatan, gabungan watak raja, wira dan pelawak dalam Jikey membantu:", options: ["Menjadikan cerita sukar difahami", "Menyeimbangkan unsur serius dan lucu", "Menghapuskan struktur cerita", "Menggantikan muzik"], correct: 1 },
      { question: "Muzik dan nyanyian dalam Jikey secara keseluruhan menonjolkan:", options: ["Tiada identiti budaya", "Suasana hiburan rakyat yang meriah", "Keheningan penuh", "Bunyi industri moden"], correct: 1 }
    ]  },
  {
    id: "bahagian-d",
    name: "Bahagian D: Konteks Sosial & Fungsi Jikey",
    icon: "🤝",
    color: "#B85C38",
    description: "Fungsi sosial, perpaduan kaum & peranan Jikey dalam masyarakat.",
    passThreshold: 70,
    maxPoints: 100,
    questions: [
      { question: "JKKN menegaskan Jikey ialah salah satu seni tradisional Melayu yang:", options: ["Hanya untuk pelancong asing", "Mencerminkan identiti dan hiburan masyarakat setempat", "Bertujuan politik semata-mata", "Terhad kepada istana"], correct: 1 },
      { question: "Dalam liputan Bernama, Jikey digambarkan sebagai lambang:", options: ["Persaingan kaum", "Perpaduan kaum", "Gerakan politik", "Perniagaan kecil"], correct: 1 },
      { question: "Persembahan Jikey pada program seperti Temasya 'Oghang' Kedah berperanan sebagai:", options: ["Sesi kuliah rasmi", "Tarikan hiburan dan warisan kepada orang ramai", "Peperiksaan awam", "Latihan tentera"], correct: 1 },
      { question: "Dari perspektif sosial, watak pelbagai bangsa dalam Jikey menunjukkan:", options: ["Pemisahan masyarakat", "Interaksi dan keakraban pelbagai etnik", "Tiada komunikasi", "Sikap anti-budaya"], correct: 1 },
      { question: "Jikey sebagai teater rakyat menyumbang kepada:", options: ["Pengasingan generasi tua muda", "Perkongsian pengalaman dan nilai antara generasi", "Penolakan tradisi", "Pendidikan sains sahaja"], correct: 1 },
      { question: "Penonton Jikey biasanya terdiri daripada:", options: ["Hanya pegawai kerajaan", "Masyarakat umum di kawasan persembahan", "Hanya pelajar universiti", "Hanya pelancong asing"], correct: 1 },
      { question: "Pementasan Jikey oleh JKKN dalam festival dan pameran bertujuan:", options: ["Menggantikan semua seni lain", "Mengenalkan dan menghidupkan semula minat terhadap seni ini", "Menutup akses publik", "Mengkomersialkan secara eksklusif"], correct: 1 },
      { question: "Dialog lucu dan usik-mengusik dalam Jikey memberi ruang kepada:", options: ["Menyindir penonton secara menghina", "Menyampaikan teguran sosial dengan cara santai", "Menyampaikan maklumat palsu", "Mengurangkan minat terhadap budaya"], correct: 1 },
      { question: "Dalam konteks komuniti, Jikey boleh dianggap sebagai:", options: ["Alat peperangan", "Medium komunikasi budaya dan identiti", "Pengganti sekolah", "Urusan kewangan"], correct: 1 },
      { question: "Dengan pementasan di acara awam, Jikey membantu:", options: ["Mengasingkan penonton mengikut kaum", "Mengeratkan interaksi antara penonton pelbagai latar", "Menghadkan akses seni budaya", "Menyekat perkembangan pelancongan"], correct: 1 },
      { question: "Sebagai seni warisan, Jikey dirujuk dalam Pemetaan Budaya untuk:", options: ["Dilupuskan dari rekod", "Dikenal pasti, didokumentasi dan difahami oleh umum", "Disimpan rahsia", "Dijadikan bahan ujian sahaja"], correct: 1 },
      { question: "Fungsi Jikey pada majlis budaya moden termasuk:", options: ["Menggantikan semua bentuk muzik lain", "Menjadi persembahan utama yang mempamerkan tradisi tempatan", "Menyekat persembahan moden", "Menggantikan ucapan perasmian"], correct: 1 },
      { question: "Dari sudut sosial, penglibatan pelakon muda dalam Jikey menyumbang kepada:", options: ["Kehilangan minat budaya", "Kelangsungan tradisi dalam komuniti", "Hanya hiburan sementara", "Penurunan perpaduan"], correct: 1 },
      { question: "Dalam kerangka pembangunan budaya negara, seni seperti Jikey menyokong:", options: ["Penghapusan identiti tempatan", "Pemeliharaan warisan tidak ketara (intangible heritage)", "Pengasingan budaya", "Peniruan budaya asing sepenuhnya"], correct: 1 },
      { question: "Penampilan Jikey di platform rasmi JKKN menunjukkan:", options: ["Ia tidak penting kepada dasar budaya", "Ia diiktiraf sebagai sebahagian penting warisan seni negara", "Ia hanya hobi individu", "Ia seni yang dilarang"], correct: 1 }
    ]  },
  {
    id: "bahagian-e",
    name: "Bahagian E: Pemuliharaan & Cabaran Kontemporari Jikey",
    icon: "🌿",
    color: "#2D7A66",
    description: "Pemuliharaan warisan, cabaran moden & usaha JKKN.",
    passThreshold: 70,
    maxPoints: 100,
    questions: [
      { question: "Menurut Bernama, status semasa Jikey di Kedah digambarkan sebagai:", options: ["Sangat rancak dan meluas", "Semakin malap dan perlu disegarkan semula", "Langsung tiada masalah", "Sudah dihapuskan secara rasmi"], correct: 1 },
      { question: "JKKN Kedah mahu pentas Jikey kembali rancak untuk:", options: ["Menjadikannya tontonan tertutup", "Menyegarkan semula persembahan tradisional Melayu ini", "Menggantikan semua seni lain", "Mengurangkan aktiviti budaya"], correct: 1 },
      { question: "Antara cabaran utama Jikey ialah:", options: ["Terlalu banyak kumpulan aktif", "Bilangan kumpulan yang sangat terhad", "Tiada sokongan JKKN", "Kekurangan lokasi persembahan rasmi"], correct: 1 },
      { question: "Laporan menyebut hanya berapa kumpulan Jikey yang masih aktif di Kedah ketika itu?", options: ["Tiada", "Satu", "Dua", "Sepuluh"], correct: 2 },
      { question: "Untuk mempopularkan semula Jikey, JKKN sering:", options: ["Menghentikan semua pementasan", "Mementaskan Jikey dalam program anjurannya", "Menghadkan kepada latihan dalaman", "Menutup pangkalan data budaya"], correct: 1 },
      { question: "Program perantisan Jikey diwujudkan oleh JKKN bagi:", options: ["Menguji pelajar secara akademik", "Mengajar generasi muda tentang seni persembahan ini", "Menggantikan pelajaran muzik di sekolah", "Menghapuskan seni moden"], correct: 1 },
      { question: "Pemetaan Budaya sebagai portal rasmi membantu pemuliharaan Jikey dengan:", options: ["Menyembunyikan maklumat kepada umum", "Menyediakan platform mudah akses maklumat seni warisan", "Menghapuskan rekod lama", "Mengganti maklumat dengan iklan"], correct: 1 },
      { question: "Salah satu langkah strategik untuk memelihara Jikey ialah:", options: ["Melarang pementasan di khalayak ramai", "Meningkatkan dokumentasi, pementasan, dan pendidikan tentang Jikey", "Menghadkan kepada arkib sahaja", "Mengabaikan program generasi muda"], correct: 1 },
      { question: "Pementasan Jikey dalam festival pelancongan budaya seperti di Langkawi berpotensi:", options: ["Mengurangkan minat terhadap warisan", "Meningkatkan kesedaran pelancong terhadap seni tradisi", "Menggantikan semua produk pelancongan lain", "Menyusutkan ekonomi tempatan"], correct: 1 },
      { question: "Antara risiko jika tiada usaha berterusan untuk Jikey ialah:", options: ["Terlalu banyak persembahan", "Kemungkinan seni ini semakin dilupakan", "Kenaikan mendadak penonton", "Penambahan kumpulan tanpa kawalan"], correct: 1 },
      { question: "Peranan komuniti setempat dalam pemuliharaan Jikey termasuk:", options: ["Menghalang pementasan", "Menyokong, menonton, dan melibatkan diri dalam latihan/pementasan", "Menghapus bahan dokumentasi", "Menggantikan semua tradisi lain"], correct: 1 },
      { question: "Penyertaan anak muda dalam program perantisan Jikey menyumbang kepada:", options: ["Pengakhiran seni tradisi", "Pewarisan kemahiran kepada generasi seterusnya", "Pengurangan kualiti persembahan", "Pengecilan komuniti budaya"], correct: 1 },
      { question: "JKKN sebagai agensi kerajaan berperanan dalam pemuliharaan Jikey dengan:", options: ["Mengabaikan seni tradisional", "Menganjur program, pementasan dan dokumentasi", "Melarang dokumentasi digital", "Mengubah Jikey kepada seni moden sepenuhnya"], correct: 1 },
      { question: "Cabaran mendokumentasikan Jikey termasuk:", options: ["Tiada teknologi", "Perlu mengekalkan keaslian sambil menyesuaikan dengan medium moden", "Larangan undang-undang", "Tiada minat masyarakat langsung"], correct: 1 },
      { question: "Secara keseluruhan, pemuliharaan Jikey memerlukan:", options: ["Usaha individu sahaja", "Pengurangan pementasan", "Kerjasama kerajaan, komuniti, penggiat seni dan generasi muda", "Penamatan semua program budaya lain"], correct: 2 }
    ]
  }
];
